/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Login
     * @description Check the demo credentials and set the HTTP-only session cookie.
     */
    post: operations['login_api_v1_auth_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Logout
     * @description Delete the session row and clear the cookie.
     */
    post: operations['logout_api_v1_auth_logout_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Me
     * @description Who is signed in. The console calls this once on every page load.
     */
    get: operations['me_api_v1_auth_me_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/hostedzones': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Hosted Zones */
    get: operations['list_hosted_zones_api_v1_hostedzones_get'];
    put?: never;
    /**
     * Create Hosted Zone
     * @description Create a zone. Route53's default SOA and NS records are created with it.
     */
    post: operations['create_hosted_zone_api_v1_hostedzones_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/hostedzones/{zone_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Hosted Zone */
    get: operations['get_hosted_zone_api_v1_hostedzones__zone_id__get'];
    put?: never;
    post?: never;
    /**
     * Delete Hosted Zone
     * @description Refused with HostedZoneNotEmpty (409) while non-default records exist.
     */
    delete: operations['delete_hosted_zone_api_v1_hostedzones__zone_id__delete'];
    options?: never;
    head?: never;
    /**
     * Update Hosted Zone
     * @description Edit the description, tags and VPC associations: everything Route53 lets you change.
     */
    patch: operations['update_hosted_zone_api_v1_hostedzones__zone_id__patch'];
    trace?: never;
  };
  '/api/v1/hostedzones/{zone_id}/records': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Record Sets */
    get: operations['list_record_sets_api_v1_hostedzones__zone_id__records_get'];
    put?: never;
    /** Create Record Set */
    post: operations['create_record_set_api_v1_hostedzones__zone_id__records_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/hostedzones/{zone_id}/records/{record_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Record Set */
    get: operations['get_record_set_api_v1_hostedzones__zone_id__records__record_id__get'];
    /**
     * Replace Record Set
     * @description Replace values, TTL and routing fields. Name and type are fixed.
     */
    put: operations['replace_record_set_api_v1_hostedzones__zone_id__records__record_id__put'];
    post?: never;
    /**
     * Delete Record Set
     * @description The default SOA and apex NS records are refused with 400.
     */
    delete: operations['delete_record_set_api_v1_hostedzones__zone_id__records__record_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/hostedzones/{zone_id}/changes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Change Record Sets
     * @description Atomic batch of CREATE / UPSERT / DELETE actions: all of it applies, or none of it.
     */
    post: operations['change_record_sets_api_v1_hostedzones__zone_id__changes_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/changes/{change_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Change
     * @description Change status. Changes apply instantly here, so this is always INSYNC.
     */
    get: operations['get_change_api_v1_changes__change_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/hostedzones/{zone_id}/import': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Import Zone File
     * @description Parse a BIND zone file. The apex SOA and NS are skipped, as Route53 keeps its own.
     */
    post: operations['import_zone_file_api_v1_hostedzones__zone_id__import_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/hostedzones/{zone_id}/export': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Export Zone */
    get: operations['export_zone_api_v1_hostedzones__zone_id__export_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description Liveness check for the hosting platform.
     */
    get: operations['health_api_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AliasTarget */
    AliasTarget: {
      /** Dns Name */
      dns_name: string;
      /** Hosted Zone Id */
      hosted_zone_id: string;
      /**
       * Evaluate Target Health
       * @default false
       */
      evaluate_target_health: boolean;
    };
    /** ChangeAction */
    ChangeAction: {
      /**
       * Action
       * @enum {string}
       */
      action: 'CREATE' | 'UPSERT' | 'DELETE';
      record_set?: components['schemas']['RecordSetCreate'] | null;
      record?: components['schemas']['RecordRef'] | null;
    };
    /** ChangeBatchRequest */
    ChangeBatchRequest: {
      /** Comment */
      comment?: string | null;
      /** Changes */
      changes: components['schemas']['ChangeAction'][];
    };
    /**
     * ChangeInfo
     * @description Returned after every write, like Route53's ChangeInfo.
     */
    ChangeInfo: {
      /** Id */
      id: string;
      /** Status */
      status: string;
      /** Comment */
      comment?: string | null;
      /**
       * Submitted At
       * Format: date-time
       */
      submitted_at: string;
    };
    /** ErrorBody */
    ErrorBody: {
      /** Code */
      code: string;
      /** Message */
      message: string;
      /**
       * Field Errors
       * @default []
       */
      field_errors: components['schemas']['FieldError'][];
    };
    /** ErrorResponse */
    ErrorResponse: {
      error: components['schemas']['ErrorBody'];
    };
    /** FieldError */
    FieldError: {
      /** Field */
      field: string;
      /** Message */
      message: string;
    };
    /** HostedZoneCreate */
    HostedZoneCreate: {
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /**
       * Type
       * @default public
       * @enum {string}
       */
      type: 'public' | 'private';
      /**
       * Vpcs
       * @default []
       */
      vpcs: components['schemas']['VPCIn'][];
      /**
       * Tags
       * @default []
       */
      tags: components['schemas']['Tag'][];
    };
    /** HostedZoneDetail */
    HostedZoneDetail: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /**
       * Type
       * @enum {string}
       */
      type: 'public' | 'private';
      /** Created By */
      created_by: string;
      /** Record Count */
      record_count: number;
      /** Description */
      description: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Caller Reference */
      caller_reference: string;
      /** Name Servers */
      name_servers: string[];
      /** Tags */
      tags: components['schemas']['Tag'][];
      /** Vpcs */
      vpcs: components['schemas']['VPCOut'][];
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** HostedZoneSummary */
    HostedZoneSummary: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /**
       * Type
       * @enum {string}
       */
      type: 'public' | 'private';
      /** Created By */
      created_by: string;
      /** Record Count */
      record_count: number;
      /** Description */
      description: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * HostedZoneUpdate
     * @description Only what Route53 lets you change after creation. Omitted fields stay as they are.
     */
    HostedZoneUpdate: {
      /** Description */
      description?: string | null;
      /** Tags */
      tags?: components['schemas']['Tag'][] | null;
      /** Vpcs */
      vpcs?: components['schemas']['VPCIn'][] | null;
    };
    /** HostedZoneWriteResponse */
    HostedZoneWriteResponse: {
      hosted_zone: components['schemas']['HostedZoneDetail'];
      change: components['schemas']['ChangeInfo'];
    };
    /** ImportLineError */
    ImportLineError: {
      /** Line */
      line: number;
      /** Message */
      message: string;
    };
    /** ImportRequest */
    ImportRequest: {
      /** Zone File */
      zone_file: string;
    };
    /**
     * ImportResult
     * @description Preview on dry_run=true; with dry_run=false the preview is committed as one change batch.
     */
    ImportResult: {
      /** Record Sets */
      record_sets: components['schemas']['RecordSetCreate'][];
      /** Errors */
      errors: components['schemas']['ImportLineError'][];
      /** Skipped */
      skipped: number;
      change?: components['schemas']['ChangeInfo'] | null;
    };
    /** LoginRequest */
    LoginRequest: {
      /**
       * Login Type
       * @default iam
       * @enum {string}
       */
      login_type: 'root' | 'iam';
      /** Account Id */
      account_id?: string | null;
      /** Username */
      username: string;
      /** Password */
      password: string;
    };
    /** Page[HostedZoneSummary] */
    Page_HostedZoneSummary_: {
      /** Items */
      items: components['schemas']['HostedZoneSummary'][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
    };
    /** Page[RecordSetOut] */
    Page_RecordSetOut_: {
      /** Items */
      items: components['schemas']['RecordSetOut'][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
    };
    /**
     * RecordRef
     * @description Identifies an existing record set for DELETE, either by ID or by identity.
     */
    RecordRef: {
      /** Id */
      id?: string | null;
      /** Name */
      name?: string | null;
      /** Type */
      type?: ('A' | 'AAAA' | 'CNAME' | 'TXT' | 'MX' | 'NS' | 'PTR' | 'SRV' | 'CAA' | 'SOA') | null;
      /** Set Identifier */
      set_identifier?: string | null;
    };
    /** RecordSetCreate */
    RecordSetCreate: {
      /**
       * Ttl
       * @default 300
       */
      ttl: number | null;
      /**
       * Values
       * @default []
       */
      values: string[];
      /**
       * Routing Policy
       * @default SIMPLE
       * @enum {string}
       */
      routing_policy:
        | 'SIMPLE'
        | 'WEIGHTED'
        | 'LATENCY'
        | 'FAILOVER'
        | 'MULTIVALUE'
        | 'GEOLOCATION'
        | 'GEOPROXIMITY'
        | 'IP_BASED';
      /** Set Identifier */
      set_identifier?: string | null;
      /** Weight */
      weight?: number | null;
      /** Region */
      region?: string | null;
      /** Failover */
      failover?: ('PRIMARY' | 'SECONDARY') | null;
      /** Health Check Id */
      health_check_id?: string | null;
      alias?: components['schemas']['AliasTarget'] | null;
      /**
       * Name
       * @default
       */
      name: string;
      /**
       * Type
       * @enum {string}
       */
      type: 'A' | 'AAAA' | 'CNAME' | 'TXT' | 'MX' | 'NS' | 'PTR' | 'SRV' | 'CAA' | 'SOA';
    };
    /** RecordSetOut */
    RecordSetOut: {
      /** Id */
      id: string;
      /** Zone Id */
      zone_id: string;
      /** Name */
      name: string;
      /**
       * Type
       * @enum {string}
       */
      type: 'A' | 'AAAA' | 'CNAME' | 'TXT' | 'MX' | 'NS' | 'PTR' | 'SRV' | 'CAA' | 'SOA';
      /** Ttl */
      ttl: number | null;
      /** Values */
      values: string[];
      /**
       * Routing Policy
       * @enum {string}
       */
      routing_policy:
        | 'SIMPLE'
        | 'WEIGHTED'
        | 'LATENCY'
        | 'FAILOVER'
        | 'MULTIVALUE'
        | 'GEOLOCATION'
        | 'GEOPROXIMITY'
        | 'IP_BASED';
      /** Set Identifier */
      set_identifier: string | null;
      /** Weight */
      weight: number | null;
      /** Region */
      region: string | null;
      /** Failover */
      failover: ('PRIMARY' | 'SECONDARY') | null;
      /** Health Check Id */
      health_check_id: string | null;
      alias: components['schemas']['AliasTarget'] | null;
      /** Is Default */
      is_default: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * RecordSetUpdate
     * @description PUT body: name and type are fixed after creation, as in the console.
     */
    RecordSetUpdate: {
      /**
       * Ttl
       * @default 300
       */
      ttl: number | null;
      /**
       * Values
       * @default []
       */
      values: string[];
      /**
       * Routing Policy
       * @default SIMPLE
       * @enum {string}
       */
      routing_policy:
        | 'SIMPLE'
        | 'WEIGHTED'
        | 'LATENCY'
        | 'FAILOVER'
        | 'MULTIVALUE'
        | 'GEOLOCATION'
        | 'GEOPROXIMITY'
        | 'IP_BASED';
      /** Set Identifier */
      set_identifier?: string | null;
      /** Weight */
      weight?: number | null;
      /** Region */
      region?: string | null;
      /** Failover */
      failover?: ('PRIMARY' | 'SECONDARY') | null;
      /** Health Check Id */
      health_check_id?: string | null;
      alias?: components['schemas']['AliasTarget'] | null;
    };
    /** RecordSetWriteResponse */
    RecordSetWriteResponse: {
      record_set: components['schemas']['RecordSetOut'];
      change: components['schemas']['ChangeInfo'];
    };
    /** Tag */
    Tag: {
      /** Key */
      key: string;
      /**
       * Value
       * @default
       */
      value: string;
    };
    /** UserOut */
    UserOut: {
      /** Id */
      id: number;
      /** Username */
      username: string;
      /** Account Id */
      account_id: string;
    };
    /** VPCIn */
    VPCIn: {
      /** Region */
      region: string;
      /** Vpc Id */
      vpc_id: string;
    };
    /** VPCOut */
    VPCOut: {
      /** Region */
      region: string;
      /** Vpc Id */
      vpc_id: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserOut'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  me_api_v1_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserOut'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  list_hosted_zones_api_v1_hostedzones_get: {
    parameters: {
      query?: {
        /** @description Matches name, description or ID */
        search?: string | null;
        type?: ('public' | 'private') | null;
        /** @description 1-based page number */
        page?: number;
        page_size?: number;
        /** @description Column to sort by */
        sort?: string | null;
        order?: 'asc' | 'desc';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page_HostedZoneSummary_'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  create_hosted_zone_api_v1_hostedzones_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['HostedZoneCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HostedZoneWriteResponse'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  get_hosted_zone_api_v1_hostedzones__zone_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        zone_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HostedZoneDetail'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  delete_hosted_zone_api_v1_hostedzones__zone_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        zone_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  update_hosted_zone_api_v1_hostedzones__zone_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        zone_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['HostedZoneUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HostedZoneWriteResponse'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  list_record_sets_api_v1_hostedzones__zone_id__records_get: {
    parameters: {
      query?: {
        /** @description Matches record name or value */
        search?: string | null;
        type?:
          ('A' | 'AAAA' | 'CNAME' | 'TXT' | 'MX' | 'NS' | 'PTR' | 'SRV' | 'CAA' | 'SOA') | null;
        routing_policy?:
          | (
              | 'SIMPLE'
              | 'WEIGHTED'
              | 'LATENCY'
              | 'FAILOVER'
              | 'MULTIVALUE'
              | 'GEOLOCATION'
              | 'GEOPROXIMITY'
              | 'IP_BASED'
            )
          | null;
        /** @description 1-based page number */
        page?: number;
        page_size?: number;
        /** @description Column to sort by */
        sort?: string | null;
        order?: 'asc' | 'desc';
      };
      header?: never;
      path: {
        zone_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page_RecordSetOut_'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  create_record_set_api_v1_hostedzones__zone_id__records_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        zone_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RecordSetCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RecordSetWriteResponse'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  get_record_set_api_v1_hostedzones__zone_id__records__record_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        record_id: string;
        zone_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RecordSetOut'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  replace_record_set_api_v1_hostedzones__zone_id__records__record_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        record_id: string;
        zone_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RecordSetUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RecordSetWriteResponse'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  delete_record_set_api_v1_hostedzones__zone_id__records__record_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        record_id: string;
        zone_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  change_record_sets_api_v1_hostedzones__zone_id__changes_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        zone_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangeBatchRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ChangeInfo'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  get_change_api_v1_changes__change_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        change_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ChangeInfo'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  import_zone_file_api_v1_hostedzones__zone_id__import_post: {
    parameters: {
      query?: {
        /** @description true returns a preview without writing anything */
        dry_run?: boolean;
      };
      header?: never;
      path: {
        zone_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ImportRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ImportResult'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  export_zone_api_v1_hostedzones__zone_id__export_get: {
    parameters: {
      query?: {
        format?: 'bind' | 'json';
      };
      header?: never;
      path: {
        zone_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/plain': unknown;
          'application/json': unknown;
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
    };
  };
}
